import { Dimensions, StyleSheet } from "react-native";
import type { AppColors } from "../../theme/colors";

const { width: SCREEN_W } = Dimensions.get("window");

export function createTaskStyles(c: AppColors) {
  return StyleSheet.create({
    container: { flex: 1, backgroundColor: c.backgroundSecondary },
    header: {
      paddingHorizontal: 24,
      paddingTop: 12,
      paddingBottom: 8,
      paddingLeft: 60,
    },
    headerTitle: { fontSize: 32, fontWeight: "900", color: c.text },
    headerDate: {
      fontSize: 14,
      fontWeight: "600",
      color: c.primary,
      marginTop: 2,
    },
    calStrip: { maxHeight: 94, flexGrow: 0 },
    dayCell: {
      width: SCREEN_W / 7,
      alignItems: "center",
      justifyContent: "center",
      paddingVertical: 10,
      borderRadius: 14,
    },
    dayCellSelected: { backgroundColor: c.primary },
    monthTag: {
      fontSize: 9,
      fontWeight: "800",
      color: c.primary,
      marginBottom: 1,
    },
    dayName: { fontSize: 11, fontWeight: "600", color: c.textMuted },
    dayNum: {
      fontSize: 18,
      fontWeight: "800",
      color: c.text,
      marginTop: 2,
    },
    dayTextSelected: { color: c.inverse },
    dayNumToday: { color: c.primary },
    todayDot: {
      width: 5,
      height: 5,
      borderRadius: 3,
      backgroundColor: c.primary,
      marginTop: 3,
    },
    todayDotSelected: { backgroundColor: c.inverse },
    progressRow: {
      flexDirection: "row",
      alignItems: "center",
      paddingHorizontal: 24,
      marginTop: 12,
      gap: 10,
    },
    progressBar: {
      flex: 1,
      height: 6,
      borderRadius: 3,
      backgroundColor: c.border,
    },
    progressFill: { height: 6, borderRadius: 3, backgroundColor: c.primary },
    progressText: { fontSize: 12, fontWeight: "700", color: c.textSecondary },
    taskList: { paddingHorizontal: 16, paddingTop: 12, paddingBottom: 100 },
    taskCard: {
      flexDirection: "row",
      alignItems: "center",
      backgroundColor: c.surface,
      borderRadius: 16,
      padding: 14,
      marginBottom: 10,
      borderWidth: 1,
      borderColor: c.border,
      shadowColor: c.shadow,
      shadowOpacity: 0.06,
      shadowRadius: 8,
      shadowOffset: { width: 0, height: 2 },
      elevation: 2,
    },
    checkWrap: { padding: 8, position: "relative" },
    checkbox: {
      width: 26,
      height: 26,
      borderRadius: 8,
      borderWidth: 2.5,
      borderColor: c.borderStrong,
      alignItems: "center",
      justifyContent: "center",
    },
    sparkle: {
      position: "absolute",
      top: -4,
      right: -4,
      fontSize: 18,
    },
    taskInfo: { flex: 1, marginLeft: 10 },
    taskTitle: { fontSize: 15, fontWeight: "700", color: c.text },
    taskTitleDone: { textDecorationLine: "line-through", color: c.textMuted },
    timeRow: {
      flexDirection: "row",
      alignItems: "center",
      gap: 4,
      marginTop: 3,
    },
    taskTime: { fontSize: 12, fontWeight: "500", color: c.textMuted },
    priorityBadge: {
      flexDirection: "row",
      alignItems: "center",
      gap: 4,
      paddingHorizontal: 8,
      paddingVertical: 4,
      borderRadius: 8,
      marginRight: 6,
    },
    priorityDot: { width: 6, height: 6, borderRadius: 3 },
    priorityText: {
      fontSize: 11,
      fontWeight: "700",
      textTransform: "capitalize",
    },
    deleteBtn: { padding: 6 },
    deleteBtnInner: {
      width: 32,
      height: 32,
      borderRadius: 10,
      backgroundColor: c.dangerSoftBg,
      alignItems: "center",
      justifyContent: "center",
      borderWidth: 1,
      borderColor: c.dangerSoftBorder,
    },
    emptyWrap: { alignItems: "center", marginTop: 80 },
    emptyEmoji: { fontSize: 48 },
    emptyTitle: {
      fontSize: 18,
      fontWeight: "800",
      color: c.textMuted,
      marginTop: 12,
    },
    emptySub: {
      fontSize: 13,
      fontWeight: "500",
      color: c.textSecondary,
      marginTop: 4,
    },
    toast: {
      position: "absolute",
      top: 60,
      alignSelf: "center",
      zIndex: 100,
    },
    toastInner: {
      flexDirection: "row",
      alignItems: "center",
      gap: 8,
      backgroundColor: c.surface,
      paddingHorizontal: 20,
      paddingVertical: 12,
      borderRadius: 50,
      shadowColor: c.shadow,
      shadowOpacity: 0.12,
      shadowRadius: 12,
      shadowOffset: { width: 0, height: 4 },
      elevation: 8,
      borderWidth: 1,
      borderColor: c.primarySoftBg,
    },
    toastText: { fontSize: 14, fontWeight: "700", color: c.text },
    fab: { position: "absolute", right: 24, zIndex: 10, elevation: 10 },
    fabGrad: {
      width: 56,
      height: 56,
      borderRadius: 18,
      alignItems: "center",
      justifyContent: "center",
      shadowColor: c.primary,
      shadowOpacity: 0.3,
      shadowRadius: 12,
      shadowOffset: { width: 0, height: 4 },
      elevation: 6,
    },
    delOverlay: {
      flex: 1,
      backgroundColor: c.overlay,
      alignItems: "center",
      justifyContent: "center",
    },
    delCard: {
      backgroundColor: c.surface,
      borderRadius: 24,
      padding: 28,
      width: SCREEN_W * 0.82,
      alignItems: "center",
      borderWidth: 1,
      borderColor: c.border,
    },
    delIconWrap: { marginBottom: 16 },
    delIconCircle: {
      width: 72,
      height: 72,
      borderRadius: 36,
      alignItems: "center",
      justifyContent: "center",
    },
    delTitle: {
      fontSize: 20,
      fontWeight: "900",
      color: c.text,
      marginBottom: 8,
    },
    delMsg: {
      fontSize: 14,
      fontWeight: "500",
      color: c.textSecondary,
      textAlign: "center",
      marginBottom: 24,
      lineHeight: 20,
    },
    delActions: { flexDirection: "row", gap: 12, width: "100%" },
    delCancelBtn: {
      flex: 1,
      paddingVertical: 14,
      borderRadius: 14,
      borderWidth: 1.5,
      borderColor: c.border,
      alignItems: "center",
    },
    delCancelText: { fontSize: 15, fontWeight: "700", color: c.textSecondary },
    delConfirmBtn: { flex: 1 },
    delConfirmGrad: {
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "center",
      gap: 6,
      paddingVertical: 14,
      borderRadius: 14,
    },
    delConfirmText: { fontSize: 15, fontWeight: "800", color: "#fff" },
    modalOverlay: {
      flex: 1,
      backgroundColor: c.overlayModal,
      justifyContent: "flex-end",
    },
    modalCard: {
      backgroundColor: c.surface,
      borderTopLeftRadius: 24,
      borderTopRightRadius: 24,
      padding: 24,
      paddingBottom: 40,
      borderTopWidth: 1,
      borderColor: c.border,
    },
    modalHeader: {
      flexDirection: "row",
      justifyContent: "space-between",
      alignItems: "center",
      marginBottom: 20,
    },
    modalTitle: { fontSize: 20, fontWeight: "800", color: c.text },
    modalLabel: {
      fontSize: 13,
      fontWeight: "700",
      color: c.textSecondary,
      marginBottom: 6,
      marginTop: 10,
    },
    modalInput: {
      backgroundColor: c.inputBg,
      borderRadius: 12,
      borderWidth: 1.5,
      borderColor: c.inputBorder,
      paddingHorizontal: 14,
      paddingVertical: 12,
      fontSize: 15,
      fontWeight: "600",
      color: c.text,
    },
    timeBtn: {
      flexDirection: "row",
      alignItems: "center",
      gap: 8,
      backgroundColor: c.inputBg,
      borderRadius: 12,
      borderWidth: 1.5,
      borderColor: c.inputBorder,
      paddingHorizontal: 14,
      paddingVertical: 13,
    },
    timeBtnText: { fontSize: 15, fontWeight: "700", color: c.text },
    reminderNote: {
      flexDirection: "row",
      alignItems: "center",
      gap: 6,
      marginTop: 10,
      paddingHorizontal: 4,
    },
    reminderNoteText: { fontSize: 12, fontWeight: "600", color: c.primaryLight },
    modalRow: { flexDirection: "row" },
    priorityRow: { flexDirection: "row", gap: 6 },
    prioBtn: {
      flex: 1,
      paddingVertical: 10,
      borderRadius: 10,
      borderWidth: 1.5,
      borderColor: c.border,
      alignItems: "center",
    },
    prioBtnText: { fontSize: 12, fontWeight: "700", color: c.textMuted },
    saveBtn: {
      backgroundColor: c.primary,
      borderRadius: 14,
      paddingVertical: 16,
      alignItems: "center",
      marginTop: 20,
    },
    saveBtnText: { fontSize: 16, fontWeight: "800", color: "#ffffff" },
    tpOverlay: {
      flex: 1,
      backgroundColor: c.overlay,
      alignItems: "center",
      justifyContent: "center",
    },
    tpCard: {
      backgroundColor: c.surface,
      borderRadius: 24,
      padding: 24,
      width: SCREEN_W * 0.82,
      maxHeight: 420,
      borderWidth: 1,
      borderColor: c.border,
    },
    tpTitle: {
      fontSize: 18,
      fontWeight: "800",
      color: c.text,
      textAlign: "center",
    },
    tpDisplay: { alignItems: "center", marginVertical: 12 },
    tpBigTime: { fontSize: 40, fontWeight: "900", color: c.primary },
    tpRow: {
      flexDirection: "row",
      alignItems: "flex-start",
      justifyContent: "center",
    },
    tpCol: { width: 90, alignItems: "center" },
    tpLabel: {
      fontSize: 11,
      fontWeight: "700",
      color: c.textMuted,
      marginBottom: 6,
    },
    tpScroll: { maxHeight: 180 },
    tpColon: {
      fontSize: 28,
      fontWeight: "900",
      color: c.borderStrong,
      marginTop: 24,
      marginHorizontal: 8,
    },
    tpCell: {
      paddingVertical: 8,
      paddingHorizontal: 16,
      borderRadius: 10,
      marginVertical: 2,
      alignItems: "center",
    },
    tpCellActive: { backgroundColor: c.primary },
    tpCellText: { fontSize: 16, fontWeight: "700", color: c.textSecondary },
    tpCellTextActive: { color: "#ffffff" },
    tpActions: { flexDirection: "row", gap: 10, marginTop: 16 },
    tpSecBtn: {
      flex: 1,
      paddingVertical: 13,
      borderRadius: 12,
      borderWidth: 1.5,
      borderColor: c.border,
      alignItems: "center",
    },
    tpSecBtnText: { fontSize: 14, fontWeight: "700", color: c.textSecondary },
    tpDoneBtn: {
      flex: 1,
      paddingVertical: 13,
      borderRadius: 12,
      backgroundColor: c.primary,
      alignItems: "center",
    },
    tpDoneBtnText: { fontSize: 14, fontWeight: "800", color: "#fff" },
  });
}

export type TaskScreenStyles = ReturnType<typeof createTaskStyles>;
